name: nightly

on:
  schedule:
    - cron: '0 8 * * *' # run at 8 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup miniconda environment
        uses: conda-incubator/setup-miniconda@master
        with:
          channels: conda-forge,nodefaults
          channel-priority: strict
          activate-environment: xdev
          auto-update-conda: false
          python-version: 3.9
          environment-file: environment.yml
          mamba-version: '*'
          use-mamba: true

      - name: Verify environment installation
        run: conda env list

      - id: 'auth'
        name: Authenticate for Google BigQuery access
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Update package download data
        run: GOOGLE_APPLICATION_CREDENTIALS=${{ steps.auth.outputs.credentials_file_path }} ./cli/getdownloads.py

      - name: Update GitHub statistics
        run: ./cli/getghstats.py

      - name: Update Packages metrics page
        run: ./cli/mkpkgs.py

      - name: Update Tutorials metrics page
        run: ./cli/mktuts.py

      - name: Commit new changes
        uses: EndBug/add-and-commit@v8
        with:
          add: '-A'
          default_author: github_actions
          message: '[skip ci] Nightly metrics updates'
